import {fileURLToPath} from 'node:url';
process.chdir(fileURLToPath(new URL('../',import.meta.url)));
// Run with HAPPY_DOM_MODULE pointing to pinned happy-dom 20.14.5 lib/index.js.
import fs from 'node:fs';import assert from 'node:assert/strict';
const {Window}=await import(process.env.HAPPY_DOM_MODULE||'./runtime/node_modules/happy-dom/lib/index.js');
const w=new Window({url:'http://localhost/'});w.document.body.innerHTML='<a class="skip-link" href="#main"></a><div id="app"></div>';w.LAB_CLASSROOM_CONFIG={enabled:true,securityReviewed:true,url:'https://classroom-test.supabase.co',publishableKey:'sb_publishable_mock'};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};
let uid='student-a',role='student',saved=[],rev=0;const requests=[];
w.fetch=async(url,options={})=>{requests.push({url,method:options.method});const path=new URL(url).pathname;let b={};try{b=JSON.parse(options.body||'{}');}catch{}let out={};if(path.endsWith('/classroom-auth'))out=b.action==='roster'?{classroom:{id:'class-a',name:'Test class'},students:[{id:'student-a',display_name:'Alice <script>'},{id:'student-b',display_name:'Bob'}]}:{session:{access_token:'fake',expires_in:3600}};else if(path.endsWith('/user'))out={id:uid};else if(path.endsWith('/classrooms'))out=[{id:'class-a',name:'Test class'}];else if(path.endsWith('/memberships'))out=[{classroom_id:'class-a',user_id:uid,display_name:uid,role,active:true}];else if(/\/(progress|engagement|submissions|comments)$/.test(path))out=[];else if(path.endsWith('/token'))out={access_token:'fake',expires_in:3600};else if(path.endsWith('/classroom-data')){if(b.action==='load-progress')out={progress:null};if(b.action==='progress'){saved.push(b);out={version:++rev};}}return {ok:true,status:200,json:async()=>out};};
const files=[...fs.readFileSync('index.html','utf8').matchAll(/<script defer src="([^"]+)"/g)].map(m=>m[1].split('?')[0]).filter(x=>!x.includes('classroom-config'));
for(const file of files)w.eval(fs.readFileSync(file,'utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));const tick=()=>new Promise(r=>setTimeout(r,15));
const el=s=>{const e=w.document.querySelector(s);assert(e,s);return e;};const click=async s=>{el(s).click();await tick();};const submit=async s=>{el(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();};
async function student(name){await click('[data-classroom-open]');el('#class-code-form input').value='class-code';await submit('#class-code-form');el('#student-login-form select').value=name;el('#student-login-form input').value='placeholder';await submit('#student-login-form');assert(el('#submission-form'));}
await student('student-a');assert.equal(w.document.querySelectorAll('#classroom-dialog script').length,0);await click('[data-act=close]');w.location.hash='#/bootcamp/first-command';w.dispatchEvent(new w.Event('hashchange'));await new Promise(r=>setTimeout(r,1400));assert(saved.length>0);assert(saved.every(s=>s.classroomId==='class-a'));assert(!Object.keys(w.localStorage).some(x=>/token|password/.test(x)));
// Exercise private export cleanup through the real renderer, not just the storage API.
const revoked=[];w.URL.createObjectURL=()=> 'blob:private-export';w.URL.revokeObjectURL=url=>revoked.push(url);
w.location.hash='#/investigation/define-problem';w.dispatchEvent(new w.Event('hashchange'));await tick();
const note=el('#capstone-notes textarea');note.value='Private Student A draft';note.dispatchEvent(new w.Event('input',{bubbles:true}));
await click('[data-action=export-notebook]');assert.match(el('#export-notes').value,/Private Student A draft/);
// Simulates a signout/account-change arriving while a private preview is open.
await click('[data-classroom-open]');await click('[data-act=signout]');assert.deepEqual(Array.from(w.LabClassroom.memberships),[]);assert.deepEqual(Array.from(w.LabClassroom.submissions),[]);assert(revoked.includes('blob:private-export'));assert.equal(w.document.querySelector('#export-notes'),null);assert.doesNotMatch(w.document.body.textContent,/Private Student A draft/);uid='student-b';await student('student-b');assert.equal(JSON.parse(w.LabClassroom.getItem('matlab-lab:v2')).progress.bootcamp.completed.length,0);await click('[data-act=signout]');uid='teacher-a';role='teacher';el('#teacher-login [name=email]').value='teacher@example.test';el('#teacher-login [name=password]').value='placeholder';await submit('#teacher-login');assert.match(el('#classroom-dialog h2').textContent,/Teacher dashboard/);assert.equal(w.document.querySelector('#submission-form'),null);
console.log('PASS: simulated DOM account login, roster escaping, scoped sync, signout cleanup, student isolation, teacher dashboard. Not a browser visual test.');await w.happyDOM.close();
