/* Project 1: one ideal, level-ground launch model shared by both languages. */
(function(root){
  const L=(en,zh)=>({en,zh});
  const setup='speed = 20;\nangle = 45;\ngravity = 9.81;';
  const components=setup+'\nvx = speed*cosd(angle);\nvy = speed*sind(angle);';
  const timeline=components+'\nflightTime = 2*vy/gravity;\nt = linspace(0, flightTime, 101);';
  const model=timeline+'\nx = vx*t;\ny = vy*t - 0.5*gravity*t.^2;';
  const graph="\nplot(x, y);\nxlabel('Distance (m)');\nylabel('Height (m)');\ntitle('Projectile motion');\ngrid on;\naxis equal;";
  const number=(id,label,answer,tolerance=0.02)=>({id,label,type:'number',answer,tolerance,placeholder:L('Enter a number (2 decimal places is enough)','输入数字（保留两位小数即可）')});
  const lessons=[
    {
      id:'launch-setup',icon:'flag',minutes:5,title:L('Choose your launch','设定发射条件'),short:L('Set the launch','设定发射'),goal:L('Turn a flying ball into a model with three inputs.','用三个输入，建立一个飞行小球的模型。'),term:'model / 模型',diagram:'launch-setup',editor:'projectile.m',
      see:L('Start at ground level. Move right and up. Gravity points down.','从地面出发，向右上方运动。重力方向向下。'),
      understand:L('Our model has no air resistance. The ball starts and lands at the same height. speed is in metres per second (m/s), angle is in degrees above horizontal, and gravity is 9.81 m/s². Positive x points right; positive y points up.','本模型忽略空气阻力，起点和落地点高度相同。speed 的单位是米/秒（m/s），angle 是与水平线的夹角，单位为度，gravity 为 9.81 m/s²。x 的正方向向右，y 的正方向向上。'),
      steps:[L('Choose New Script in MATLAB. Save it as projectile.m in your current folder. Type the code below in the Editor.','在 MATLAB 中选择 New Script，把脚本保存为当前文件夹中的 projectile.m。在编辑器中输入下面的代码。'),L('Click Run. If MATLAB asks, choose Change Folder. Read the three values in the Command Window. Each later mission provides a complete script: replace the editor contents with that mission’s code, then run it.','点击 Run。如果 MATLAB 询问，请选择 Change Folder。在命令窗口中读取三个数值。后续每个任务都提供完整脚本：用该任务的代码替换编辑器内容，再运行。')],
      code:setup+'\n[speed angle gravity]',output:'ans =\n\n   20.0000   45.0000    9.8100',
      compare:L('The three values appear in this order: speed, angle, gravity. Extra zeros do not change a value.','三个数值的顺序是 speed、angle、gravity。小数末尾的零不会改变数值。'),
      note:L('This is an ideal model, not a real-world prediction with wind or drag. Keep gravity positive; we will use a minus sign for its downward effect.','这是理想模型，不包含风和空气阻力。gravity 保持为正数，之后用减号表示它向下的作用。'),
      questions:[{id:'units',label:L('What unit does speed use?','speed 使用什么单位？'),type:'choice',answer:'m/s',options:[{value:'m',label:L('Metres (m)','米（m）')},{value:'m/s',label:L('Metres per second (m/s)','米/秒（m/s）')},{value:'degrees',label:L('Degrees (°)','度（°）')}]},number('gravity',L('What value is stored in gravity?','gravity 中保存的数值是多少？'),9.81,0.001)],
      hint:L('Speed tells us how many metres the ball travels each second. Read gravity from the third line.','速度表示每秒移动多少米。gravity 的值在第三行。'),success:L('Launch conditions set. Next, separate sideways speed from upward speed.','发射条件已设定。接下来，把水平方向和竖直方向的速度分开。')
    },
    {
      id:'speed-components',icon:'steps',minutes:5,title:L('Split one speed into two','把速度分成两个方向'),short:L('Split the speed','分解速度'),goal:L('Find the sideways and upward parts of the launch.','求出发射速度的水平分量和竖直分量。'),term:'component / 分量',diagram:'speed-components',editor:'projectile.m',
      see:L('vx moves right. vy moves up. Together, they make the launch velocity.','vx 向右，vy 向上。两者合起来，就是发射速度。'),
      understand:L('Use `vx = speed*cosd(angle)` and `vy = speed*sind(angle)`. These formulas split a velocity into two directions. The d in cosd and sind means degrees. `cos` and `sin` use radians, a different angle unit.','用 `vx = speed*cosd(angle)` 和 `vy = speed*sind(angle)`，把速度分解到两个方向。cosd 和 sind 中的 d 表示角度以“度”为单位。`cos` 和 `sin` 使用另一种角度单位：弧度。'),
      steps:[L('Replace the script with the code below. Keep speed = 20 and angle = 45.','用下面的代码替换脚本。保持 speed = 20，angle = 45。'),L('Run it. [vx vy] shows the horizontal value first, then the vertical value. At 45°, the two values match.','运行脚本。[vx vy] 先显示水平分量，再显示竖直分量。在 45° 时，两者相同。')],code:components+'\n[vx vy]',output:'ans =\n\n   14.1421   14.1421',
      compare:L('Each component is about 14.14 m/s. They are not 20 + 20: the original velocity is the diagonal of the right triangle.','两个分量均约为 14.14 m/s。它们不是 20 + 20：原来的速度对应直角三角形的斜边。'),note:L('Use these values at full precision in MATLAB. Only round the answers you type on this page.','在 MATLAB 中保留数值的完整精度。只需对本页输入的答案进行四舍五入。'),
      questions:[number('vx',L('What is vx at 45°? (m/s)','45° 时 vx 是多少？（m/s）'),Math.SQRT2*10),{id:'degrees',label:L('Which function accepts an angle in degrees?','哪个函数接收以“度”为单位的角度？'),type:'choice',answer:'sind',options:[{value:'sind',label:L('sind','sind')},{value:'sin',label:L('sin','sin')}]}],hint:L('Read the first value in [vx vy]. For degrees, remember the extra d.','读取 [vx vy] 的第一个数值。使用“度”时，记住多出来的 d。'),success:L('About 14.14 m/s to the right and 14.14 m/s up. Both directions start at the same time.','向右约 14.14 m/s，向上约 14.14 m/s。两个方向的运动同时开始。')
    },
    {
      id:'flight-time',icon:'clock',minutes:5,title:L('Build time up to landing','建立到落地为止的时间序列'),short:L('Flight time','飞行时间'),goal:L('Give the model a start, an end, and 101 moments between them.','为模型设定起止时间，并用 101 个时刻描述飞行。'),term:'flight time / 飞行时间',diagram:'flight-time',editor:'projectile.m',
      see:L('Half the flight goes up. Half comes down.','飞行时间的一半用于上升，另一半用于下降。'),
      understand:L('For this same-height model, `flightTime = 2*vy/gravity`. The upward speed reaches zero after vy/gravity seconds; falling back takes the same time. `linspace(0, flightTime, 101)` makes 101 evenly spaced values including both ends.','对于起落高度相同的模型，`flightTime = 2*vy/gravity`。经过 vy/gravity 秒，向上的速度降到零；回落需要相同时间。`linspace(0, flightTime, 101)` 生成 101 个等间距数值，包括两端。'),
      steps:[L('Run the complete script below. linspace takes a start, a stop, and a number of values; its third input is not a step size.','运行下面的完整脚本。linspace 的输入为起点、终点和数值个数；第三个输入不是步长。'),L('t(1) selects the first time, t(end) selects the last, and numel(t) counts the values. Read all three results.','t(1) 取出第一个时刻，t(end) 取出最后一个时刻，numel(t) 统计数值个数。读取这三个结果。')],code:timeline+'\n[t(1) t(end) numel(t)]',output:'ans =\n\n         0    2.8832  101.0000',
      compare:L('The timeline begins at 0 s and ends at about 2.8832 s. There are 101 values and 100 gaps.','时间从 0 秒开始，在约 2.8832 秒结束。共有 101 个数值、100 个间隔。'),note:L('The middle entry, t(51), is exactly halfway through this timeline. We will use it to find the top of the flight.','中间的 t(51) 恰好是飞行总时间的一半。之后用它来找到最高点。'),questions:[number('time',L('What is the total flight time? (s)','飞行总时间是多少？（秒）'),2*Math.SQRT2*10/9.81),number('count',L('How many values are in t?','t 中有多少个数值？'),101,1e-8)],hint:L('The final time is the second displayed value. The 101 in linspace is the number of values, not seconds.','最后的时刻是显示结果中的第二个值。linspace 中的 101 是数值个数，不是秒数。'),success:L('About 2.88 seconds, sampled at 101 moments. Your model now knows when to stop.','约 2.88 秒，取 101 个时刻。模型现在知道何时结束了。')
    },
    {
      id:'trajectory-values',icon:'cells',minutes:6,title:L('Calculate the whole path','计算完整轨迹'),short:L('Build the trajectory','建立轨迹'),goal:L('Use the same time vector for sideways motion and height.','用同一个时间向量，计算水平位置和高度。'),term:'trajectory / 轨迹',diagram:'trajectory-values',editor:'projectile.m',
      see:L('One time. One x value. One y value. One position.','一个时刻，一个 x 值，一个 y 值，对应一个位置。'),understand:L('`x = vx*t` gives distance when horizontal speed is constant. `y = vy*t - 0.5*gravity*t.^2` starts with upward motion, then subtracts gravity’s effect. The dot in `t.^2` squares each time value. x and y have matching positions.','水平速度不变时，`x = vx*t` 给出水平距离。`y = vy*t - 0.5*gravity*t.^2` 先计算向上运动，再减去重力的影响。`t.^2` 中的点号对每个时间值分别平方。x 和 y 的对应项组成位置。'),
      steps:[L('Run the script below. It computes all 101 x and y values at once. Keep the minus sign and the dot in .^.','运行下面的脚本，一次算出全部 101 个 x 和 y 值。保留减号和 .^ 中的点。'),L('Read the midpoint [x(51) y(51)]. Then type y(end) in the Command Window to check the landing height.','读取中点 [x(51) y(51)]。然后在命令窗口输入 y(end)，检查落地高度。')],code:model+'\n[x(51) y(51)]',output:'ans =\n\n   20.3874   10.1937',
      compare:L('Halfway through the flight, the ball is about 20.39 m right and 10.19 m high. y(end) should be zero or extremely close to zero.','飞行到一半时，小球向右约 20.39 米，高约 10.19 米。y(end) 应为零，或非常接近零。'),note:L('A result like -7.1e-15 at landing is rounding noise: it is about 0.000000000000007 m below zero. It does not mean the ball travels underground.','落地时 -7.1e-15 这样的结果是舍入误差，约为零以下 0.000000000000007 米，不代表小球进入地下。'),questions:[number('height',L('What is y(51), the height halfway through the flight? (m)','y(51)，即飞行到一半时的高度，是多少？（米）'),100/9.81),{id:'gravity-sign',label:L('Why do we subtract 0.5*gravity*t.^2?','为什么减去 0.5*gravity*t.^2？'),type:'choice',answer:'down',options:[{value:'down',label:L('Gravity acts downward','重力向下作用')},{value:'right',label:L('Gravity pushes the ball right','重力把小球推向右边')}]}],hint:L('Read the second midpoint value. Our positive y direction is upward, so gravity reduces y.','读取中点的第二个数值。y 的正方向向上，所以重力使 y 减小。'),success:L('The midpoint is about 10.19 m high. Matching entries in x and y describe the same instant.','中点高度约为 10.19 米。x 和 y 的对应项描述同一个时刻。')
    },
    {
      id:'flight-plot',icon:'plot',minutes:5,title:L('Draw the flight','画出飞行轨迹'),short:L('Plot the flight','绘制轨迹'),goal:L('See the model as a path through space.','把模型显示为空间中的一条轨迹。'),term:'axis / 坐标轴',diagram:'flight-plot',editor:'projectile.m',
      see:L('Plot height against distance, not against time.','用距离作横轴、高度作纵轴，而不是用时间作横轴。'),understand:L('`plot(x, y)` joins the positions in time order. Each point is a place in space. `axis equal` makes one metre on the horizontal axis the same screen length as one metre on the vertical axis.','`plot(x, y)` 按时间顺序连接各个位置。每个点表示空间中的一个位置。`axis equal` 使横轴上的一米与纵轴上的一米在屏幕上长度相同。'),steps:[L('Run the complete script. Look in the figure window or Figures panel.','运行完整脚本，查看图形窗口或 Figures 面板。'),L('Check the axis labels. The ball should start at (0, 0), reach one high point, and land back on y = 0.','检查坐标轴标签。小球应从 (0, 0) 出发，到达一个最高点，再落回 y = 0。')],code:model+graph,outputPlot:'projectile-45',
      compare:L('Your path should peak near (20.39, 10.19) and land near (40.77, 0). The curve has 101 sampled points. Tick spacing, colors and margins may differ.','轨迹最高点应接近 (20.39, 10.19)，落地点接近 (40.77, 0)。曲线包含 101 个采样点。刻度间距、颜色和留白可能不同。'),note:L('plot(t, y) would show height over time, a different graph. Use plot(x, y) to show the trajectory.','plot(t, y) 显示高度随时间变化，是另一种图像。显示轨迹时，请使用 plot(x, y)。'),questions:[{id:'horizontal',label:L('What does the horizontal axis show here?','这张图的横轴表示什么？'),type:'choice',answer:'distance',options:[{value:'distance',label:L('Distance in metres','距离，单位：米')},{value:'time',label:L('Time in seconds','时间，单位：秒')}]},number('landing',L('Run x(end). Where does the ball land? (m)','运行 x(end)。小球落在多远处？（米）'),400/9.81)],hint:L('Read xlabel. For landing distance, x(end) selects the final horizontal position.','读取 xlabel。x(end) 取出最后的水平位置，也就是落地距离。'),success:L('About 40.77 m. You have plotted a trajectory with physical units.','约 40.77 米。你已经绘制了一条带物理单位的轨迹。')
    },
    {
      id:'flight-measures',icon:'target',minutes:4,title:L('Read the two big numbers','读出两个关键数值'),short:L('Range and height','射程与高度'),goal:L('Measure how far and how high the ball travels.','测量小球飞多远、飞多高。'),term:'range / 射程',diagram:'flight-measures',editor:'projectile.m',
      see:L('Range is horizontal. Maximum height is vertical.','射程是水平距离，最大高度是竖直距离。'),understand:L('Range is the horizontal distance from launch to landing. Here it is `x(end)`, because launch x is 0. `max(y)` finds the largest sampled height. Our 101-point timeline includes the exact midpoint, so it includes the peak of this symmetric flight.','射程是发射点到落地点的水平距离。这里起点 x 为 0，所以射程是 `x(end)`。`max(y)` 找出采样高度中的最大值。101 点时间序列包含准确的时间中点，因此包含这次对称飞行的最高点。'),steps:[L('Run the code. range and maxHeight are new variable names for measurements.','运行代码。range 和 maxHeight 是用来保存测量结果的新变量名。'),L('Compare the two values with the graph in the previous mission.','把这两个数值与上一任务中的图像对比。')],code:model+'\nrange = x(end);\nmaxHeight = max(y);\n[range maxHeight]',output:'ans =\n\n   40.7747   10.1937',
      compare:L('The first value is range, about 40.77 m. The second is maximum height, about 10.19 m. These are different measurements.','第一个值是射程，约 40.77 米。第二个值是最大高度，约 10.19 米。它们是不同的测量量。'),note:L('More sample points can improve a sampled maximum. With an even number of points, you may miss the exact peak and get a slightly smaller max(y).','增加采样点可以改善采样最大值。点数为偶数时，可能错过准确的最高点，得到略小的 max(y)。'),questions:[number('range',L('Enter the range. (m)','输入射程。（米）'),400/9.81),number('height',L('Enter the maximum height. (m)','输入最大高度。（米）'),100/9.81)],hint:L('Keep the order of the bracketed output: range first, maximum height second.','注意方括号中的顺序：先射程，后最大高度。'),success:L('40.77 m across and 10.19 m up. You can now compare launches using numbers.','水平约 40.77 米，最高约 10.19 米。现在你可以用数值来比较不同发射。')
    },
    {
      id:'angle-investigation',icon:'steps',minutes:6,title:L('Change one thing','只改变一个条件'),short:L('Compare angles','比较角度'),goal:L('Keep the speed fixed and investigate three launch angles.','保持速度不变，研究三个发射角度。'),term:'fair comparison / 公平比较',diagram:'angle-investigation',editor:'projectile.m',
      see:L('Same speed. Same gravity. Three different angles.','相同速度，相同重力加速度，三个不同角度。'),understand:L('For same-height flights without drag, `range = speed^2*sind(2*angle)/gravity`. This comes from vx multiplied by flightTime. Use the angle vector [30 45 60] to calculate all three ranges. Change only the angle to make a fair comparison.','忽略阻力、起落高度相同时，`range = speed^2*sind(2*angle)/gravity`，即 vx 乘以 flightTime。使用角度向量 [30 45 60]，一次计算三个射程。只改变角度，才能公平比较。'),steps:[L('Run the script below. speed is a single number, so speed^2 does not need a dot. sind works on every angle in the vector.','运行下面的脚本。speed 是单个数值，因此 speed^2 不需要点号。sind 会对向量中的每个角度计算。'),L('Read ranges in the Command Window and match them to the three points. The lines only connect the three tested angles.','在命令窗口读取 ranges，并与图中的三个点对应。连线只连接这三个已测试的角度。')],code:"speed = 20;\ngravity = 9.81;\nangles = [30 45 60];\nranges = speed^2*sind(2*angles)/gravity;\nplot(angles, ranges, '-o');\nxlabel('Angle (degrees)');\nylabel('Range (m)');\ntitle('Same speed, different angles');\ngrid on;\nranges",outputPlot:'angle-ranges',
      compare:L('Ranges are about 35.31, 40.77 and 35.31 m. The 45° launch goes farthest of these three. The 30° and 60° launches have equal range but different heights.','射程约为 35.31、40.77、35.31 米。在这三个角度中，45° 发射最远。30° 和 60° 的射程相同，但高度不同。'),note:L('45° is optimal only for this ideal same-height model. Different landing heights or air resistance can change the best angle.','45° 最优只适用于这个起落高度相同的理想模型。落地高度不同或存在空气阻力时，最佳角度可能改变。'),questions:[{id:'ranges',label:L('Enter the ranges for 30°, 45°, 60°, in order. (m)','按顺序输入 30°、45°、60° 的射程。（米）'),type:'vector',answer:[400*Math.sin(Math.PI/3)/9.81,400/9.81,400*Math.sin(Math.PI/3)/9.81],tolerance:0.03,placeholder:L('Three numbers, rounded to 2 decimals','三个数值，保留两位小数')},number('best',L('Which tested angle gives the greatest range? (degrees)','测试的哪个角度射程最大？（度）'),45,1e-8)],hint:L('Read ranges from left to right. Compare the middle value with the other two.','从左到右读取 ranges。比较中间的数值与另外两个数值。'),success:L('30° and 60° both reach about 35.31 m. Keep that result: your final mission has a target around 35 m.','30° 和 60° 都能到达约 35.31 米。记住这个结果：最后的任务有一个约 35 米处的目标区。')
    },
    {
      id:'target-challenge',icon:'flag',minutes:8,title:L('Mission: land in the zone','任务：落入目标区'),short:L('Target challenge','目标挑战'),goal:L('Choose a launch that lands between 34 and 36 metres.','选择一种发射方式，使小球落在 34 到 36 米之间。'),term:'prediction / 预测',diagram:'target-challenge',editor:'target_launch.m',download:'downloads/projectile_starter.m',
      see:L('Your target is 34–36 m away. Choose 30° or 60°.','目标区在 34–36 米处。请选择 30° 或 60°。'),understand:L('Keep speed at 20 m/s and gravity at 9.81 m/s². Your last investigation showed two angles with the same range. Choose either angle, predict the landing distance, then run the full model to test it. The two paths have different peak heights.','保持 speed 为 20 m/s，gravity 为 9.81 m/s²。上一项研究发现，两个角度具有相同射程。任选一个，预测落地距离，再运行完整模型进行检验。两条轨迹的最大高度不同。'),steps:[L('Download the starter or copy the code below into a new script. Replace ___ with 30 or 60. Save as target_launch.m.','下载起始脚本，或将下方代码复制到新脚本中。把 ___ 替换为 30 或 60，并保存为 target_launch.m。'),L('Run it and compare the landing position with the target zone. The reference shows both possible paths; your MATLAB plot shows only your chosen path.','运行脚本，把落地点与目标区对比。参考图显示两条可选轨迹；MATLAB 图中只显示你选择的轨迹。'),L('Choose your angle below and enter the range and peak height printed by your own script. Both correct solutions are accepted.','在下方选择你的角度，并输入脚本输出的射程和最大高度。两种正确方案都可以通过。')],code:setup.replace('angle = 45;','angle = ___;')+'\nvx = speed*cosd(angle);\nvy = speed*sind(angle);\nflightTime = 2*vy/gravity;\nt = linspace(0, flightTime, 101);\nx = vx*t;\ny = vy*t - 0.5*gravity*t.^2;'+graph.replace("'Projectile motion'","'Target launch'")+'\nrange = x(end);\nmaxHeight = max(y);\n[range maxHeight]',outputPlot:'target-paths',
      compare:L('Both paths land near 35.31 m, inside the target zone. At 30° the peak is about 5.10 m; at 60° it is about 15.29 m. Your angle and height must agree.','两条轨迹都落在约 35.31 米处，位于目标区内。30° 的最高点约为 5.10 米，60° 约为 15.29 米。你选择的角度与输入的高度必须对应。'),note:L('If MATLAB reports an error at ___, replace it with your chosen angle. If the range is about 40.77 m, you are still using 45°.','如果 MATLAB 在 ___ 处报错，请把它替换为选择的角度。如果射程约为 40.77 米，说明你仍在使用 45°。'),questions:[{id:'angle',label:L('Which angle did you use?','你使用了哪个角度？'),type:'choice',answers:['30','60'],options:[{value:'30',label:L('30° · lower path','30° · 较低轨迹')},{value:'60',label:L('60° · higher path','60° · 较高轨迹')}]},number('range',L('Enter your landing distance. (m)','输入你的落地距离。（米）'),400*Math.sin(Math.PI/3)/9.81,0.03),{...number('height',L('Enter your maximum height. (m)','输入你的最大高度。（米）'),0,0.03),dependsOn:'angle',answersByValue:{'30':50/9.81,'60':150/9.81}}],hint:L('Use the range and maxHeight output, not a position index. The 30° solution is the lower arc. Both solutions should land between 34 and 36 m.','使用 range 和 maxHeight 的输出，不要输入位置编号。30° 对应较低的弧线。两种方案都应落在 34 到 36 米之间。'),success:L('Target reached. You set assumptions, built a model, checked its output, and tested a prediction. Save your script and show the graph to your teacher.','命中目标！你设定了假设、建立了模型、检查了结果，并检验了预测。请保存脚本，把图像展示给老师。')
    }
  ];
  root.PROJECTILE={id:'projectile-motion',version:1,lessons};
  if(typeof module!=='undefined')module.exports=root.PROJECTILE;
})(typeof window!=='undefined'?window:globalThis);
